services:
  backend:
    build: .
    image: atreus-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./backend/atreus_indexer.db:/app/backend/atreus_indexer.db
    restart: always

  indexer:
    build: .
    image: atreus-backend
    command: ["node", "backend/dist/indexer.js"]
    env_file:
      - .env
    volumes:
      - ./backend/atreus_indexer.db:/app/backend/atreus_indexer.db
    restart: always
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - prometheus
